#postgresql:
#  image: docker2.molflow.com/odin_redo/odin_db:latest
#  ports:
#    - 5432:5432
#  environment:
#    - POSTGRES_PASSWORD:test

webapi:
  image: docker2.molflow.com/odin/microq:latest
  ports:
    - 5000:5000
  volumes:
    - ./src/:/app
    - ./data/:/var/lib/odindata
  links:
    - mysqlhost

mysqlhost:
  image: docker2.molflow.com/devops/hermod_mysql
  environment:
    - MYSQL_ROOT_PASSWORD=empty
    - MYSQL_DATABASE=smr
    - MYSQL_USER=odinuser
    - MYSQL_PASSWORD=***REMOVED***
  ports:
    - localhost:3306:3306
