#postgresql:
#  image: docker2.molflow.com/odin_redo/odin_db:latest
#  ports:
#    - 5432:5432
#  environment:
#    - POSTGRES_PASSWORD:test

webapi:
  image: docker2.molflow.com/odin/microq:latest
  ports:
    - 5000:5000
  environment:
    - USERVICE_DATABASE_URI=mysql+pymysql://testuser:secret@mysqlhost/smr
    - USERVICE_ADMIN_USER=admin
    - USERVICE_ADMIN_PASSWORD=sqrrl
  volumes:
    - ./src/:/app
    - ./data/:/var/lib/odindata
  links:
    - mysqlhost

uworker:
  image: docker2.molflow.com/devops/odinapi_mcr
  # Normal entrypoint does not work because of mount of volume
  entrypoint: [python, /app/uworker/uworker.py]
  # For interactive mode
  #stdin_open: true
  #tty: true
  environment:
    - UWORKER_HOSTNAME=test_host
    - UWORKER_CONTAINER_NAME=test_container
    # Start with timeout to test qsmr job failure
    # - UWORKER_JOB_TIMEOUT=10
    - UWORKER_JOB_API_ROOT=http://webapi:5000/rest_api
    - UWORKER_JOB_API_PROJECT=testproject
    - UWORKER_JOB_API_USERNAME=worker1
    - UWORKER_JOB_API_PASSWORD=sqrrl
    - UWORKER_EXTERNAL_API_USERNAME=test
    - UWORKER_EXTERNAL_API_PASSWORD=test
  volumes:
    - ./src/:/app
  links:
    - webapi

mysqlhost:
  image: docker2.molflow.com/devops/hermod_mysql
  environment:
    - MYSQL_ROOT_PASSWORD=empty
    - MYSQL_DATABASE=smr
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=secret
  ports:
    - localhost:3306:3306
